[project]
name = "decisiontree"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

typeCheckingMode = "standard"
